### ISSUE TITLE
Fix code scanning alert - Information exposure through an exception

### ISSUE THREAD

**Issue by malvads** [redBorder/rb-aioutliers#41]
Tracking issue for:
- [ ] https://github.com/redBorder/rb-aioutliers/security/code-scanning/1

**Comment by malvads** [comment]
@PRodriguezFlores Last commit added this security issue, assigning to you to fix in the next PR, can be fixed by throwing an error like "Error while executing outliers"

**Comment by PRodriguezFlores** [comment]
Solved in PR-39
